[project]
name = "mcp-pdf"
version = "0.1.0"
description = "MCP server for handling PDF"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.9.0",
    "pillow>=11.2.1",
    "pymupdf>=1.26.1",
    "pymupdf4llm>=0.0.25",
]

[dependency-groups]
dev = ["ruff>=0.12.0"]
